version: '3'
services:
  streamlit:
    build: ./streamlit
    ports:
      - 8501:8501
    command: streamlit run /opt/app/app.py
    networks:
      - app_network
    container_name: streamlit
  api:
    build: ./api
    ports:
      - 8000:8000
    command: python /opt/app/api.py
    networks:
      - app_network
    container_name: api

networks:
  app_network:
